#!/bin/bash

sudo apt update && sudo apt-get install -y xinetd telnetd &&\
sudo ./openvpn-install.sh &&\
sudo apt-get install -y python3-pip &&\
sudo pip3 install flask &&\
sudo bash -c 'echo "management localhost 7505" >> /etc/openvpn/server/server.conf'
sudo sysctl -p /etc/sysctl.conf
sudo service openvpn restart &&\
#sudo nohup python3 app.py &
