#!/bin/bash

new_client () {
	# Generates the custom client.ovpn
	{
	sudo cat /etc/openvpn/server/client-common.txt
	echo "<ca>"
	sudo cat /etc/openvpn/server/easy-rsa/pki/ca.crt
	echo "</ca>"
	echo "<cert>"
	sudo sed -ne '/BEGIN CERTIFICATE/,$ p' /etc/openvpn/server/easy-rsa/pki/issued/"$1".crt
	echo "</cert>"
	echo "<key>"
	sudo cat /etc/openvpn/server/easy-rsa/pki/private/"$1".key
	echo "</key>"
	echo "<tls-crypt>"
	sudo sed -ne '/BEGIN OpenVPN Static key/,$ p' /etc/openvpn/server/tc.key
	echo "</tls-crypt>"
	} > ~/"$1".ovpn
}
cd /etc/openvpn/server/easy-rsa
sudo ./easyrsa --days=360 build-client-full "$1" nopass
new_client "$1"
