#!/bin/bash

echo "var1 = 1" > file_a.py
touch 1.ovpn
cat << EOF >> ./app.py
import base64
import sys
import subprocess
import os


from flask import Flask
app = Flask(__name__)

def getVarFromFile(filename):
    import imp
    f = open(filename)
    global data
    data = imp.load_source('data', '', f)
    f.close()

def re_write(new):
    with open("file_a.py", 'r') as file:
        new_file = []
        for line in file:
            if "var1" in line:
                new_file.append(line.split("var1")[0] + "var1 = " + new + "")
            else:
                new_file.append(line)
        with open("file_a.py", 'w') as file:
            for line in new_file:
                file.writelines(line)
    file.close()


@app.route('/')
def hello_world():
    getVarFromFile('file_a.py')
    temp = data.var1
    print("check -1"+str(temp))
    r = '/home/ubuntu/'+str(temp)+'.ovpn'
    os.remove(r)
    temp = temp + 1
    re_write(str(temp))
    client = str(temp)
    print(temp)
    subprocess.check_call(['/home/ubuntu/scriptGenereCert.sh', client])
    encoded = ""

    with open(client+".ovpn") as f:
        mystr = f.readlines()
        strcomp = ""
        for line in mystr:
            strcomp += line
        strcomp = bytes(strcomp, encoding='utf-8')
        encoded = base64.b64encode(strcomp)
        encodedStr = str(encoded,"utf-8")
        #print(encodedStr)
    return (encodedStr)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=80)
EOF


cat << EOF >> ./scriptGenereCert.sh
#!/bin/bash

new_client () {
	# Generates the custom client.ovpn
	{
	sudo cat /etc/openvpn/server/client-common.txt
	echo "<ca>"
	sudo cat /etc/openvpn/server/easy-rsa/pki/ca.crt
	echo "</ca>"
	echo "<cert>"
	sudo sed -ne '/BEGIN CERTIFICATE/,$ p' /etc/openvpn/server/easy-rsa/pki/issued/"\$1".crt
	echo "</cert>"
	echo "<key>"
	sudo cat /etc/openvpn/server/easy-rsa/pki/private/"\$1".key
	echo "</key>"
	echo "<tls-crypt>"
	sudo sed -ne '/BEGIN OpenVPN Static key/,$ p' /etc/openvpn/server/tc.key
	echo "</tls-crypt>"
	} > ~/"\$1".ovpn
}
cd /etc/openvpn/server/easy-rsa
sudo ./easyrsa --days=360 build-client-full "\$1" nopass
new_client "\$1"
EOF

cat << EOF >> ./install.sh
#!/bin/bash
sudo apt update && sudo apt-get install -y xinetd telnetd &&\
wget https://git.io/vpn -O openvpn-install.sh &&\
chmod +x openvpn-install.sh &&\
sudo ./openvpn-install.sh &&\
sudo apt-get install -y python3-pip &&\
sudo pip3 install flask &&\
./scriptGenereCert.sh client
sudo service openvpn start
sudo python3 app.py
sudo bash -c 'echo "management localhost 7505" >> /etc/openvpn/server/server.conf'
sudo sysctl -p /etc/sysctl.conf
sudo service openvpn restart
sudo reboot
EOF

chmod +x scriptGenereCert.sh
chmod +x app.py
chmod +x install.sh
./install.sh
