#!/bin/bash
#./easyrsa --batch --req-cn=test gen-req test nopass
client=$1

if [ x$client = x ]; then
	echo "Usage: $0 clientname"
    	exit 1
fi

if [ ! -e keys/$client.key ]; then
    echo "Generating keys..."
    . vars
    ./pkitool $client
    echo "...keys generated."
fi

#source vars && "$EASY_RSA/pkitool" client
mkdir clients && 
cp /usr/share/doc/openvpn/examples/sample-config-files/client.conf clients/$client.ovpn
sed -i '/;user nobody/s/;//' ./clients/$client.ovpn
sed -i '/;group nogroup/s/;//' ./clients/$client.ovpn
#
sed -i '/ca ca.crt/s/ca ca.crt/#ca ca.crt/' ./clients/$client.ovpn
sed -i '/cert client.crt/s/cert client.crt/#cert client.crt/' ./clients/$client.ovpn
sed -i '/key client.key/s/key client.key/#key client.key/' ./clients/$client.ovpn
sed -i '/tls-auth ta.key 1/s/tls-auth ta.key 1/#tls-auth ta.key 1/' ./clients/$client.ovpn
#client change proto tcp et le port et ajoute server a cote remote

cat << EOF >> ./clients/$client.ovpn
<ca>
#Here goes the content of the ca.crt file
</ca>
<cert>
#Here goes the content of the cert file
</cert>
<key>
#Here goes the content of the key file
</key>

key-direction 1
<tls-auth>
# The content of the ta.key file
</tls-auth>
EOF
